/* eslint-disable react-hooks/rules-of-hooks */
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Map from "../assets/mapa-velka.png";
import Outside from "../assets/venek.jpg";
import Modal from "../components/Modal";
import ModalMini from "../components/ModalMini";
import useWindowDimensions from "../hooks/useWindowDimension";

const contact = () => {
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const { width, height } = useWindowDimensions();
  const [showModal, setShowModal] = useState(false);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid  xl:grid-cols-3 2xl:grid-cols-8 bg-cover 2xl:h-[550px] m-4  bg-motive">
        <div className="flex flex-col justify-between p-8 2xl:col-span-2">
          <div>
            <p className="pb-4">Kontakt:</p>
            <p>Terapie pod Špilberkem - psychologické centrum,</p>
            <p>První patro - pracovna č. 1, 2</p>
            <p>Údolní 222/5</p>
            <p className="pb-4">602 00, Brno - město.</p>
            <p className="pb-8">IČO: 09495673</p>
          </div>
          {width && (
            <>
              <button
                type="button"
                onClick={() => setShowModal(true)}
                className="self-center w-full p-4 font-bold transition-all duration-150 ease-linear border-2 border-black border-solid rounded shadow focus:outline-none focus:ring-2 focus:ring-white hover:opacity-75 hover:bg-slate-400"
              >
                Kontakt a domluva setkání
              </button>
              {width && width > 1282 ? (
                <Modal showModal={showModal} setShowModal={setShowModal} />
              ) : (
                <ModalMini showModal={showModal} setShowModal={setShowModal} />
              )}
            </>
          )}
        </div>
        <div className="relative 2xl:col-span-4" style={{ width: "100", height: "550px" }}>
          <Image src={Map} alt="Mapa" objectPosition="center" objectFit="cover" layout={"fill"} />
        </div>
        <div className="relative 2xl:col-span-2" style={{ width: "100%", height: "550px" }}>
          <Image src={Outside} alt="Venkovní prostor" objectPosition="center" objectFit="cover" layout={"fill"} />
        </div>
      </div>
    </div>
  );
};

export default contact;
