import Head from "next/head";
import Image from "next/image";
import ProfileImg from "../assets/profilovka.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid xl:grid-cols-2 2xl:grid-cols-3 bg-cover p-10 gap-4 2xl:h-[550px] m-4  bg-motive bg-red">
        <div className="2xl:col-span-2">
          <p>Pracuji s dětmi a dospívajícími s:</p>
          <ul className="p-4 ml-4 list-disc">
            <li>ADHD a projevy nepozornosti, hyperaktivity a impulzivity v chování, </li>
            <li>obtížemi ve vztazích s vrstevníky, učiteli a kteří se dostávají do konfliktů s rodiči,</li>
            <li>nízkým sebevědomím, důvěrou ve vlastní schopnosti a možnost změny,</li>
            <li>psychosomatickými obtížemi (např. bolesti břicha a hlavy při odchodu do školy),</li>
            <li>obtížemi ve zvládání vzteku,</li>
            <li>úzkostnými projevy v chování,</li>
            <li>depresivními projevy v chování a častou změnou nálad.</li>
          </ul>
          <p className="pb-4">Rodičům dětí nabízím konzultace.</p>
          <p>
            Jsem tu dále pro dospělé, kteří se v životě cítí být něčím omezováni, nebo se opakovaně dostávají do situací, kterým
            chtějí více porozumět a umět s nimi lépe pracovat. Také tu jsem pro ty, kteří se dostali do složité životní situace,
            ve které se potřebují zorientovat a rozhodnout se, jakým směrem se vydat. V neposlední řadě tu jsem pro ty, kteří
            chtějí pracovat na svém osobním růstu a seberozvoji. Obrátit se na mě je možné například ohledně:
          </p>
          <ul className="p-4 ml-4 list-disc">
            <li>konfliktů a nespokojenosti v partnerských vztazích,</li>
            <li>psychosomatických obtíží,</li>
            <li>úzkostí, přetrvávajícího smutku a depresivních myšlenek,</li>
            <li>náročných životních událostí a traumatických zážitků,</li>
            <li>osobního růstu a seberozvoje.</li>
          </ul>
        </div>
        <div className="self-center">
          <Image placeholder="blur" layout="responsive" objectFit="contain" src={ProfileImg} alt="Profilová fotka" />
        </div>
      </div>
    </div>
  );
}
