import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="m-2">
        <p>
          Esse incididunt eu esse nulla et nostrud sint duis cupidatat qui in laborum adipisicing aliqua. Quis officia anim aute
          id fugiat. Sit veniam enim aute consectetur. Eiusmod ad mollit aliqua dolore. Dolore irure consectetur cillum qui ea
          aliqua voluptate officia laborum. Officia tempor minim ullamco voluptate commodo commodo magna. Mollit deserunt ex ad
          occaecat enim tempor cillum fugiat.
        </p>
      </div>
    </div>
  );
}
